baseURL = "https://physcat-decal.com/"
languageCode = "en-us"
title = "PhysCat DeCal"
theme = "hugo-theme-bootstrap4-blog"
copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
paginate = 1

[params]

author = "Aled Cuda and Aditya Sengupta"
description = "Class Homepage "
custom_css = ["css/style.css"]

[[menu.sidebar]]
name = "Syllabus"
url = "https://aditya-sengupta.github.io/PhysCat_DeCal_Syllabus.pdf"

[[menu.sidebar]]
name = "Lecture Recordings"
url = "https://www.youtube.com/playlist?list=PLF4gvjw0nvoZjtqbQC8_GSrNQDLYTURZp"

[[menu.sidebar]]
name = "Lecture and OH Zoom"
url = "https://berkeley.zoom.us/j/94139582667?pwd=anM0aXlpN1l4VzBlNWhoVFQwTUJ5dz09"
