baseURL = "https://physcatdecal.github.io/"
languageCode = "en-us"
title = "PhysCat DeCal"
theme = "hugo-theme-bootstrap4-blog"
copyright = "Except where otherwise noted, content on this site is licensed under a [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by-sa/4.0/)."
paginate = 1

[params]

author = "Aled Cuda and Aditya Sengupta"
description = "Class Homepage "
custom_css = ["css/style.css"]

[params.sidebar]
about = "[PhysCat](/about) is a 2 unit Scientific and High Performance Computing Decal being offered this spring..."
